name: documentation

on:
  push:
    branches: [main]

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule update --init ndk/ofm
          git submodule update --init ndk/core
          git submodule update --init ndk/cards/agi-fh400g
          git submodule update --init ndk/cards/dk-dev-1sdx-p
          git submodule update --init ndk/cards/dk-dev-agi027res
          git submodule update --init ndk/cards/fb4cgg3
          git submodule update --init ndk/cards/fb2cghh
      - name: Setup and build
        run: |
          sudo apt-get install python3-pip
          pip3 install sphinx sphinx-vhdl sphinx_rtd_theme
          sphinx-build -M html doc/source public
          touch public/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public/html
